
// Initialise. If the database doesn't exist, it is created
var lib = new localStorageDB("visual_thermometer_db");
   
// Check if the database was just created. Useful for initial database setup
if( lib.isNew() ) {

    // create the "pages" table (ID is autogenerated)
    lib.createTable("pages", ["description","pageOrder"]);
    
    // create the "pictures" table
    lib.createTable("pictures", ["keyword","imageData"]);
    
    // create the "pages_pictures" table
    lib.createTable("pages_pictures", ["page_ID","picture_ID","order"]);
    
    // TODO: add other tables?
    
    // commit the database to localStorage
    lib.commit();
}   
