// TODO: eventually this stuff shouldn't be in the global namespace...

var lib = null;

function create_database() { 

	// Initialise. If the database doesn't exist, it is created
	lib = new localStorageDB("visual_thermometer_db");
	   
	// Check if the database was just created. Useful for initial database setup
	if( lib.isNew() ) {

		// create the "pages" table (ID is autogenerated)
		lib.createTable("pages", ["description","pageOrder"]);

		// create the "pictures" table
		lib.createTable("pictures", ["keyword","imageData"]);

		// create the "pages_pictures" table
		lib.createTable("pages_pictures", ["page_ID","picture_ID","order"]);

		// TODO: add other tables?

		// commit the database to localStorage
		lib.commit();
	}

}
create_database();


function delete_database() {
	lib.drop('visual_thermometer_db');
}


function load_db_with_samples(){
	var page = new Page();
	page.description = "Neat images";
	page.save();

	var pic = new Picture();
	pic.imageData = "data:image/gif;base64,R0lGODlhEAAQAMQAAORHHOVSKudfOulrSOp3WOyDZu6QdvCchPGolfO0o/XBs/fNwfjZ0frl3/zy7////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAkAABAALAAAAAAQABAAAAVVICSOZGlCQAosJ6mu7fiyZeKqNKToQGDsM8hBADgUXoGAiqhSvp5QAnQKGIgUhwFUYLCVDFCrKUE1lBavAViFIDlTImbKC5Gm2hB0SlBCBMQiB0UjIQA7";
	pic.save();

	page.addPicture(pic.ID);

	var pic2 = new Picture();
	pic2.imageData = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUAAAD///+l2Z/dAAAAM0lEQVR4nGP4/5/h/1+G/58ZDrAz3D/McH8yw83NDDeNGe4Ug9C9zwz3gVLMDA/A6P9/AFGGFyjOXZtQAAAAAElFTkSuQmCC";
	pic2.save();

	var page2 = new Page();
	page2.description = "another page";
	page2.save();
	page2.addPicture(pic2.ID);
}